name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Create Google services JSON
      run: |
        echo '{
          "project_info": {
            "project_number": "151511940947",
            "project_id": "rvfiles-27",
            "storage_bucket": "rvfiles-27.firebasestorage.app"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:151511940947:android:6ccb82ada026b6cfcaaba6",
                "android_client_info": {
                  "package_name": "me.rve.files"
                }
              },
              "oauth_client": [],
              "api_key": [
                {
                  "current_key": "GOOGLE_API_KEY"
                }
              ],
              "services": {
                "appinvite_service": {
                  "other_platform_oauth_client": []
                }
              }
            }
          ],
          "configuration_version": "1"
        }' > app/google-services.json
    - name: Get Google API key
      run: |
        sed -i 's/"current_key": "GOOGLE_API_KEY"/"current_key": "$GOOGLE_API_KEY"/g' app/google-services.json
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    - name: Build with Gradle
      run: ./gradlew assembleDebug lintVitalRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RvFiles-debug
        path: app/build/outputs/apk/debug/app-debug.apk
