name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Get Google API key
      run: |
        sed -i 's/"current_key": "GOOGLE_API_KEY"/"current_key": "$GOOGLE_API_KEY"/g' app/google-services.json
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    - name: Build with Gradle
      run: ./gradlew assembleDebug lintVitalRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RvFiles-debug
        path: app/build/outputs/apk/debug/app-debug.apk
